name: Python File Monitoring Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Sesuaikan dengan versi Python yang kamu gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 app.py --ignore=E501

    - name: Run app script
      run: |
        python app.py
      env:
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
